#pragma once

#include "LSPtr.h"
#include <gl/glew.h>
#include <map>

namespace Leviathan
{
	namespace Renderer
	{
		class IOpenGLTextureObject;

		class OpenGLObjectManager
		{
		public:
			OpenGLObjectManager();

			/*
			 ***************************************** Resource generation
			 * Every object resource should be generated by Object Manager.
			 */
			bool CreateTextureResource(GLuint texture_object_uid, GLuint width, GLuint height, const GLvoid* data, LSPtr<IOpenGLTextureObject>& out);
			bool CreateTextureResource(GLuint texture_object_uid, GLuint width, GLuint height, GLuint depth, const GLvoid* data, LSPtr<IOpenGLTextureObject>& out);

			bool GetTextureResource(GLuint texture_object_uid, LSPtr<IOpenGLTextureObject>& out);

		private:
			std::map<GLuint, LSPtr<IOpenGLTextureObject>> m_texture_objects;
		};
	}
}
